name: linter

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # - name: Setup PHP
      #   uses: shivammathur/setup-php@v2
      #   with:
      #     php-version: '8.4'

      # - name: Install Laravel Dependencies
      #   working-directory: ./src
      #   run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install Frontend Dependencies
        working-directory: ./public
        run: npm install

      # - name: Run Pint
      #   working-directory: ./src
      #   run: vendor/bin/pint

      - name: Format Frontend
        working-directory: ./public
        run: npm run format

      - name: Lint Frontend
        working-directory: ./public
        run: npm run lint

      # - name: Test Frontend
      #   working-directory: ./public
      #   run: npm run test

      # - name: Commit Changes
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: fix code style
      #     commit_options: '--no-verify'
